branch-defaults:
  master:
    environment: content-publisher-prod
    group_suffix: null
  prod:
    environment: content-publisher-prod
  stage:
    environment: content-publisher-stage
    group_suffix: null
global:
  application_name: content-publisher
  default_ec2_keyname: aws-deploy-keys
  default_platform: Python 2.7
  default_region: eu-central-1
  profile: eb-cli
  sc: git
